### ISSUE TITLE
Headless and No-Menu - Can't have elements inside

### ISSUE THREAD

**Issue by SonoranBrian** [quasarframework/quasar-ui-qwindow#11]
I'm hoping to change the default menu to a custom "Windows" style menu with minimize, maximize and close. This way I can have a simple tab system, and it makes for better user immersion with my app.

I've added the `headless` and `no-menu` options to the `q-window` but this makes the entire content window draggable and unable to have inputs, buttons, etc.

A quick example image of what I'm trying to do:
![image](https://user-images.githubusercontent.com/56844125/67456391-702faf80-f5e5-11e9-8dd4-7c5b79be982b.png)

If I add the `headless` tag to remove the top draggable header, the entire content area becomes a drag only section. I've been trying to find the right CSS classes to make only the top custom toolbar (`q-bar`) draggable, but have not had any luck. I've also tried adding `draggable="false"` to the content div section, but that doesn't seem to work either.

Is there any additional CSS classes I could add to only make my custom `q-bar` at the top draggable and still be able to interact with buttons and inputs below on a `headless` window?

Thank you!

**Comment by hawkeye64** [comment]
Thanks for the info. Unfortunately, I have to do a full rewrite on QWindow because it does not work at all with Firefox. :( When I do the rewrite, I will take this into consideration.
I am looking for ideas when it is headless, maybe it should not do the drag at all? What do you think?

**Comment by SonoranBrian** [comment]
@hawkeye64 Thanks for the reply!
When the window is headless, ideally the window shouldn't drag at all. This way you can add a custom header (with a q-bar or something) and make the custom header draggable. I like the ease of use with the current q-window menu, but for my application, I was hoping to make something with a bit more of a "windows" feel with the traditional minimize, maximize and close buttons at the top.

Also, I was hoping to create a simple tab system when the windows were minimized. When the window was hidden, but not closed, I would add a little window tab item onto a horizontal scroll or something. Then users could click on the tabs to re-open them. Not sure if anything like this could be partially implemented into the rewrite itself, that may be a bit out of the scope of the q-window plugin. I planned on using some sort of Vue injection so I could have multiple of the same window components on the screen.

I understand the re-write will be quite a time-consuming project. Is that something that is planned more for the future, as in possibly a couple months from now? Either way, Quasar has been a fantastic framework so far and I look forward to using it in future projects!

**Comment by SonoranBrian** [comment]
Another possibility for customizing the header would be to allow custom templates for the header. This would be similar to how the `q-table` component allows you to add in custom components to the top with `<template v-slot:top></template>`. Not sure if that would make things easier. That way you don't have to specify a draggable area somewhere in a custom top bar when `headless` is enabled.

**Comment by hawkeye64** [comment]
I will remove the draggable part when headless. You're right, it should at that point be static.

**Comment by hawkeye64** [comment]
@SonoranBrian QWindow drag and drop has been rewritten and now works with Firefox. I am ready to get back into other issues. Please test with latest (if still interested) and get back to me on your thoughts.

**Comment by xrnv2** [comment]
> Another possibility for customizing the header would be to allow custom templates for the header. This would be similar to how the `q-table` component allows you to add in custom components to the top with `<template v-slot:top></template>`. Not sure if that would make things easier. That way you don't have to specify a draggable area somewhere in a custom top bar when `headless` is enabled.

Hello,
If the above is a lot of work maybe pass a class name of draggable element will be easier and more elastic for developer, for example like in this library https://mauricius.github.io/vue-draggable-resizable/?path=/info/basic--basic-component-with-drag-handle :)

**Comment by PMeira** [comment]
> QWindow drag and drop has been rewritten and now works with Firefox. I am ready to get back into other issues. Please test with latest (if still interested) and get back to me on your thoughts.

@hawkeye64 I can confirm the basics work (Chrome/Firefox/Edge on Windows), but scrolling break it. Interestingly, it's smoother on Firefox. 

I tried to find where the issue was and it seems that it's enough to account for the scrolling in `__canBeSelected` or before calling it. For example, replacing the two instances of `this.__canBeSelected(x, y)` with `this.selected = this.__canBeSelected(x - this.scrollX, y - this.scrollY)` in `ui/src/components/QWindow.js` makes it work.

**Comment by hawkeye64** [comment]
@PMeira Can you create a new issue with this info? Thanks :heart:

**Comment by SonoranBrian** [comment]
> I will remove the draggable part when headless. You're right, it should at that point be static.

It's been quite some time but I'm looking back at the reworked Q-Window. I have the Q-Window setup but want to have a custom header. Instead of a dropdown menu I'd like to have a Q-Bar at the top and add my own maximize, minimize, and pin toggles.

It looks like there is still only one `default` slot. Is it possible to create a `header` slot? Or have my custom top bar be not "draggable" with some sort of CSS class?

![image](https://user-images.githubusercontent.com/56844125/116301049-73fd3e80-a754-11eb-91a3-d0cb6c3fa198.png)

**Comment by hawkeye64** [comment]
@SonoranBrian Add a feature request for this. I am slammed at work right now, plus trying to get QCalendar v4 into beta. I can't say when I'll be able to do this. My apologies. And, quite frankly, this is one of the app-ext's I am thinking of deprecating unless someone from the community wants to maintain it. Just a heads-up as I am undecided right now.

**Comment by SonoranBrian** [comment]
Thank you, I'll add in a feature request but appreciate the possible depreciation warning.
