### ISSUE TITLE
Drag a qWindows outside the Browser

### ISSUE THREAD

**Issue by jdriesen** [quasarframework/quasar-ui-qwindow#12]
Hi,

First of all, I wish you a fast recovery !
(read in another thread you had a surgery ...)

My question:
Is it possible to drag a qWindow outside the "browser" ?

Let me clarify.
I'm using 2 screen.
On my right hand screen, Chrome is opened in "full screen" mode.
I'm testing qWindow via https://quasarframework.github.io/app-extension-qwindow/examples  .

Now, it seems I can't drag a qWindow to my 2nd screen.
Seems that the "browser-tab" is the main container of qWindow.
Is this correct ?

Thanks in advance for your reply,

Kind regards,
Johnny Driesen
Belgium

**Comment by hawkeye64** [comment]
@jdriesen I haven't heard of this issue. The code is using the Browser Drag and Drop API. Unfortunately, the way this was done does not work with Firefox. It needs to be rewritten to use mousedown, mousemove, mouseup, etc. That might fix your issue, I don't know.

**Comment by jdriesen** [comment]
Hi @hawkeye64 ,
Thanks for your quick reply.

Well, by the fact your code is using the "Browser Drag & Drop API", I think everything is controlled by the "Browser" window (i.e. container).

Maybe that explains why it ain't possible to drag  "outside" the browser (like: to another screen)

Gonna do some further investigation on it.

Just a question: any idea when when this software will be rewritten ?

THANKS again for sharing this great plugin.

**Comment by hawkeye64** [comment]
I have a lot on my plate right now. Really, I have no idea - it's kind of in limbo, but it's always bugging me in my mind. So, no definite answer, but soon, I hope. But, it will be at least a month out until I finish my current project (madewithquasar website)

**Comment by jdriesen** [comment]
Hi @hawkeye64 

Thanks for your reply.
Take your time, though, to be honest, I'm looking forward to your solution.

Meanwhile I wish you ALL SUCCESS with your "MadeWithQuasar" website.
(please let me know when it's finished. I'm curious :) )

PS.: I've been playing a bit with https://golden-layout.com/ but I more prefer your solution (cleaner code).

Kind regards,

Johnny Driesen
Belgium.

**Comment by hawkeye64** [comment]
Never heard of it before. It's very cool, but from what I see, offers something totally different.

**Comment by jdriesen** [comment]
Hi @hawkeye64 ,

I hope you're doing well.
I was wondering how your "MadeWithQuasar" project is going on.

Reason I'm asking this...
We are planning to change our Vue front-end component library from "another-popular-one" to Quasar.
(This is a company-wide decision with quite some impact)

It's my task to convince my colleagues to switch to Quasar :)
That's why I was asking about the current situation of your "MadeWithQuasar" project...
(so I'm able to show my colleagues some extra examples)

Main reason for our change: Quasar supports all build modes... 

As far as I can see, Quasar is capable to support all features we're currently using in our App...
(and it supports them in all browsers... we already did some tests...)

We're just missing one feature: 
The enduser should be able to drag and drop components "outside" the App to a second screen.
That's a core functionality of our App, and it's a business requirement...

As written before... "Golden-Layout" is supporting this feature.
In fact, I should say "was", cause the component isn't maintained anymore, and it's still rather buggy.
So, we certainly need a 'replacement' for GL.
I've been spending some time to try to find a suitable external library, though I couldn't find a suitable one .

So, we're really looking forward to your "Q-Window" solution for FireFox (and maybe the "drag-outside-App" possibility will be solved at the same time :) )

Without willing to put any pressure on it... 
Can you maybe give me an idea when you'll have some time to work on this component ?
(I know this might be a difficult one for you, but it's just to inform my colleagues...)

Thanks in advance for your reply,

Johnny

**Comment by hawkeye64** [comment]
The madewithquasar site is temporarily on hold. Super busy at work at the moment and also need some component management updates. I how to get back to mwq soon.

I looked at Golden-Layout. It's very nice and supersedes anything QWindow does or perhaps will ever do.

**Comment by hawkeye64** [comment]
@jdriesen I am going to close this issue. I am unsure someone could write a component that can be dragged from one tab/DOM to another tab/DOM. At least not without some intermediatary like a browser extension that can act as a bridge.
The latest QWindow has been rewritten and released. v1.0.0-beta.1 - please give it try. Thanks.
