### ISSUE TITLE
Windows drags stutter and lag on Windows, fine on Mac...

### ISSUE THREAD

**Issue by rwdim** [quasarframework/quasar-ui-qwindow#13]
On Chrome OSX Catalina, drags occur mostly fine regardless of the content of the window. 

If I add expandables to the window content, and test on windows, it drags, waits, drags, waits, and while it still follows the mouse eventually, it's incredibly slow.

I profiled it using VueTools dev extension and it still renders 45fps but the window only moves 80-120 pixels at a time between delays.

Any thoughts?

Thanks - Randy

p.s. The demo site also lags for me... I'm running a 1050Ti with 32-cores and 64GB of ram, no other processes running... 

![ezgif-4-e285907b3131](https://user-images.githubusercontent.com/416537/82160290-e6ce1c00-9859-11ea-9c83-c557583a5063.gif)

**Comment by rwdim** [comment]
I will dive into the code and see if I can find the issue, perhaps take a look at the firefox issue as well.

**Comment by rwdim** [comment]
Not sure why you're rendering the entire window every time you move... the DOM already knows about the window content, once you're drawn it... but the code forces a redraw of the entire window, including the body, on every onDrag event....  The larger the body content, the slower the render...

Is this something quasar requires?  

To test it, I added:
```
        if (this.state.dragging)
          return false;
```
to the first line of  the __renderBody function, and dragging speed is almost native... like 80%..

Every other dragging module I've seen simply updates the position of the draggable item and lets the DOM handle the displaying of content. I'm worried that if Quasar requires this sort of frame-by-frame control of the rendering, it's not going to be viable in any large application.

Thoughts?
Randy

**Comment by hawkeye64** [comment]
No thought. This need to either go away of have an entire rewrite.

FYI, it does not work at all with Firefox.

**Comment by jdriesen** [comment]
Looking forward to your FF solution, @hawkeye64 .

**Comment by hawkeye64** [comment]
@jdriesen Yeah, me too :rofl: 
Just have to find the time...

**Comment by hawkeye64** [comment]
@rwdim @jdriesen v1.0.0-beta.1 has been released. The drag and drop has been completely rewritten using a different API.
Can you please test and let me know how it goes for you?

**Comment by hawkeye64** [comment]
Closing for lack of response. If you feel this is still an issue, please re-open.
