### ISSUE TITLE
Not compatible with @quasar/app v2.0.0

### ISSUE THREAD

**Issue by lyf1350** [quasarframework/quasar-ui-qwindow#14]
App · ⚠️  Extension(@quasar/qwindow): Dependency not found - @quasar/quasar-app-extension-colorize. Please install it.

App · ⚠️  Extension(@quasar/colorize): is not compatible with @quasar/app v2.0.0. Required version: ^1.0.0

**Comment by hawkeye64** [comment]
@lyf1350 Thanks for making me aware of this. I'll try to get to this on the weekend.

**Comment by kanich** [comment]
Today with the latest quasar version the compatibility problem still exists as it was described by @lyf1350 .

**Comment by hawkeye64** [comment]
Sorry guys. I am working on this now. Hop to have some fixes released today or tomorrow.

**Comment by hawkeye64** [comment]
ok, running a bit behind on this, so hopefully some time this week.

**Comment by kanich** [comment]
I only wanted to give some feedback. The timing is completely up to you. Thank you very much for all your quasar extensions.

**Comment by hawkeye64** [comment]
@kanich yes, it may not be this week. But, soon I hope (hopefully before end of month).

**Comment by hawkeye64** [comment]
@kanich Just letting you know, I have been working on this. Hope to have a release soon. For now, it'll be in the `next` branch

**Comment by kanich** [comment]
Thanks for the information. I was trying to build-up some experiments with next branch but I failed on for me unusual code structure. I shall wait for new npm extension release.

**Comment by kanich** [comment]
Thanks for the information. I was trying to build-up some experiments with next branch but I failed on for me unusual code structure. I shall wait for new npm extension release.

**Comment by hawkeye64** [comment]
@kanich Yes, it's a work in progress and has some issues I need to iron out first.

**Comment by hawkeye64** [comment]
@kanich Just letting you know I have rewritten the drag/drop. It all works on Firefox (finally!)
Still ironing out some minor issues and have to do some extensive testing with mobile.
This repo will get renamed to `quasar-ui-qwindow`
Look for a release (hopefully!) some time next week.

**Comment by kanich** [comment]
@hawkeye64 Thank you for the status info.

**Comment by hawkeye64** [comment]
Fixed in v1.0.0-beta.1
