### ISSUE TITLE
SASS syntax error: ui/src/css/QWindow.sass

### ISSUE THREAD

**Issue by jaredthirsk** [quasarframework/quasar-ui-qwindow#18]
ui/src/css/QWindow.sass line 42

`flex-wrap: nowrap;`

Should not have semicolon.

(I upgraded my deps and it is now refusing to build unless I fix all SASS syntax errors including this one.)
PS: hello from Calgary

**Comment by hawkeye64** [comment]
@jaredthirsk Thanks for reporting! :heart: I have a fix coming soon

**Comment by hawkeye64** [comment]
Fix is in v1.0.0-beta.4

**Comment by hawkeye64** [comment]
And hello back from Calgary. We shoudl meet after pandemic. :+1:
