### ISSUE TITLE
QWindow attaches to other window after selection upon dragging

### ISSUE THREAD

**Issue by cmcleese** [quasarframework/quasar-ui-qwindow#19]
When multiple QWindows are open and the upon selecting one window (without dragging) then selecting a different QWindow and dragging it, the other window "attaches" itself to the one being dragged.

**To Reproduce**
1. Go to https://codepen.io/cmcleese/pen/qBabLyJ
2.  Follow on screen steps

**Screenshots**
![qwindow](https://user-images.githubusercontent.com/2061466/101180331-ba3dee00-364b-11eb-803e-386f8d4c092e.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome 86

**Comment by hawkeye64** [comment]
@cmcleese Well, this is new to me. Thanks for letting me know. :heart:

**Comment by hawkeye64** [comment]
Will be fixed in v1.0.0-beta.5
https://codepen.io/Hawkeye64/pen/bGwEXLd

**Comment by cmcleese** [comment]
Thanks. works good
