### ISSUE TITLE
QWindow selection selects all windows if stacked upon one another instead of only the first one

### ISSUE THREAD

**Issue by cmcleese** [quasarframework/quasar-ui-qwindow#20]
QWindow selection selects all windows if stacked upon one another instead of only the first one.

**To Reproduce**
1. Go to https://codepen.io/cmcleese/pen/qBabLyJ
2. Click the title bar in different areas and notice the window selection change 

**Expected behavior**
Only the first QWindow should be selected

**Screenshots**
![selection](https://user-images.githubusercontent.com/2061466/101353336-b7353e80-3893-11eb-9d53-cc64ac359cb6.gif)

**Comment by hawkeye64** [comment]
@cmcleese Thanks for bringing this to my attention.

**Comment by hawkeye64** [comment]
Fixed in v1.0.0-beta.6
https://codepen.io/Hawkeye64/pen/yLaVYXK
