### ISSUE TITLE
Scrolling breaks interaction

### ISSUE THREAD

**Issue by PMeira** [quasarframework/quasar-ui-qwindow#21]
**Describe the bug**
When a window is floating, scrolling the document (or its container in general) breaks the window interaction.

Reproducible with v1.0.0-beta.6.

**To Reproduce**

1. Go to https://codepen.io/pmeira/pen/LYRybGN
2. Click on menu "︙", then "Float"
3. Move the floating QWindow down a bit
4. Scroll the document down
5. Try to move the floating window again -- it doesn't work as expected

**Expected behavior**
As long as the floating window is visible and unpinned, interactions should work the same regardless of the scrolling state of its container.

**Desktop**
 - OS: Windows
 - Browsers: Firefox 84, Edge 87, Chrome 87

**Additional context**

The issue can be also seen on the lives examples at https://quasarframework.github.io/quasar-ui-qwindow/examples

To fix it, it seems that it's enough to account for the scrolling in `__canBeSelected` or before calling it. For example, replacing the two instances of `this.__canBeSelected(x, y)` with `this.selected = this.__canBeSelected(x - this.scrollX, y - this.scrollY)` in `ui/src/components/QWindow.js` makes it work correctly.

**Comment by hawkeye64** [comment]
@PMeira I really appreciate you putting good reproducible steps in that I could understand. And! A fix that works! :heart:

**Comment by hawkeye64** [comment]
Fixed in v1.0.0-beta.7
