### ISSUE TITLE
Cant not move and resize

### ISSUE THREAD

**Issue by liug74** [quasarframework/quasar-ui-qwindow#6]
This Project can not move and resize in firefox browser.

**Comment by hawkeye64** [comment]
Thanks for reporting this. I'll be investigating.

**Comment by jigarzon** [comment]
Entered here to report same thing!

**Comment by hawkeye64** [comment]
Unfortunately, I have not found a fix to Firefox that doesn't involve rewriting the whole thing to not use Drag-and-Drop for the moving. Looking for suggestions.

**Comment by hawkeye64** [comment]
Looks like I'll have to rewrite QWindow to use mouseup/mousedown/mousemove. :(

**Comment by liug74** [comment]
Hard work, has the problem been solved?

**Comment by hawkeye64** [comment]
@liug74 no, sorry. I just had some back issues and just had an operation on Friday. Hoping I'll recover quickly so I can get onto this.

**Comment by liug74** [comment]
I wish you a speedy recovery and all the best!

**Comment by ioanwurf** [comment]
Hi,   I have just been bitten by this bug too. @hawkeye64 I hope you have been fully recovered.

**Comment by hawkeye64** [comment]
All, I start physiotherapy tomorrow - thanks for the concern.

**Comment by hawkeye64** [comment]
Sorry for not updating this one. The rewrite has occurred and all should be working now. Closing this ticket.
